
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build-backend:
    docker:
      - image: cimg/node:19.8.1
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: backend
      - run:
          name: Build backend
          command: yarn --cwd backend
      # - run:
      #     name: Build frontend
      #     command: yarn --cwd frontend build
      # - run:
      #     name: Build api-docs
      #     command: yarn --cwd path/to/api-docs build
      - store_artifacts:
          path: |
            backend/build
            frontend/build
          destination: builds

  build-frontend:
    docker:
      - image: cimg/node:19.8.1
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: backend
      - run:
          name: Build FRONTEND
          command: yarn --cwd frontned build
      - store_artifacts:
          path: |
            frontend/build
          destination: builds

workflows:
  version: 2
  build:
    jobs:
      - build-backend:
          filters:
            branches:
              only: main
      - build-frontend:
          filters:
            branches:
              only: main
