
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference


version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build-frontend:
    docker:
      - image: cimg/node:19.8.1
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: frontend
      - run:
          name: Install dependencies
          command: |
            cd frontend
            yarn install
      - run:
          name: Build frontend
          command: |
            cd frontend
            yarn build
      - store_artifacts:
          path: |
            frontend/build
          destination: builds

  # build-backend:
  #   docker:
  #     - image: cimg/node:19.8.1
  #   executor: node/default
  #   steps:
  #     - checkout
  #     - node/install-packages:
  #         pkg-manager: npm
  #         app-dir: backend
  #     # - run:
  #     #     name: Build backend
  #     #     command: yarn
  #     - run:
  #         name: Run test for the application
  #         command: yarn test:unit
  #     - store_artifacts:
  #         path: |
  #           backend/build
  #         destination: builds

  unit-test-backend:
    docker:
      - image: cimg/node:19.8.1
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: backend
      - restore_cache:
          key: dependency-cache-{{ checksum "backend/package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            cd backend
            yarn
      - run:
          name: Build backend
          command: yarn
      - run:
          name: Run test for the application
          command: yarn --cwd backend test:unit
      - run:
          name: Send coverage data to Coveralls
          command: |
            yarn --cwd backend coverage
      - save_cache:
          key: dependency-cache-{{ checksum "backend/package-lock.json" }}
          paths:
            - ./backend/node_modules
      - store_artifacts:
          path: |
            backend/build
          destination: builds

workflows:
  version: 2
  build:
    jobs:
      - unit-test-backend:
          filters:
            branches:
              only: main
      # - build-frontend:
      #     filters:
      #       branches:
      #         only: main
